### ISSUE TITLE
Handle Item Type metadata

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#10]
Find maps to dcterms, foaf, or bibo terms and classes?
Create a vocabulary for a site's remaining Item Type metadata?

**Comment by patrickmj** [comment]
Item Type Element | OS property
----------------- | -----------
Text |
Interviewer |        bibo:interviewer
Interviewee |        bibo:interviewee
Location |
Transcription |
Local URL |
Original Format | dcterms:format
Physical Dimensions | dcterms:extent
Duration |            dcterms:extent
Compression |
Producer |
Director  |          bibo:director
Bit Rate/Frequency |
Time Summary |
Email Body |
Subject Line |
From |
To |
CC |
BCC |
Number of Attachments |
Standards |
Objectives |
Materials |
Lesson Plan Text   | dcterms:instructionalMethod?
URL         |
Event Type |
Participants |
Birth Date |
Birthplace |
Death Date |
Occupation |
Biographical Text |
Bibliography |


Item Types | OS Class
----------- | --------------
Text          |  dctype:Text
Moving Image  |  dctype:MovingImage
Oral History  |  
Sound         |  dctype:Sound
Still Image   |  dctype:StillImage
Website       |  
Event         |  dctype:Event
Email |
Lesson Plan     |
Hyperlink |
Person     |     foaf:Person
Interactive Resource |    dctype:InteractiveResource
Dataset  |       dctype:Dataset
Physical Object | dctype:PhysicalObject
Service        | dctype:Service
Software        | dctype:Software

**Comment by zerocrates** [comment]
Have you considered the possibility of doing manual mapping, either for the "leftovers" and the custom elements, or for everything?

**Comment by patrickmj** [comment]
Not sure what you mean by 'manual mapping', but here's what I'm thinking:

For what's in the table, map over those classes and elements to the classes and properties on Omeka S.

For leftovers and custom elements, create a new vocabulary with a URI based on the Omeka 2 site's endpoint (like `http://whatevomeka.org/vocabulary`), and create properties as needed in that.

I also thought about doing that wholesale, just putting all the item types and item type elements into an Omeka 2 site-specific vocabulary (like `http://whatevomeka.org/itemtypes`), and stuffing all the import data into that one vocab.

So far, I've been leaning toward finding mappings to the vocabularies that are present on installation, and treating leftovers/custom item type metadata separately. 

Could also do both, I suppose, and duplicate data, so, for example, same data from original site would be in `bibo:producer` and in `whatevomeka:producer`. But I'm less happy about that duplication.

**Comment by patrickmj** [comment]
The extra-crazy option is to produce a mapping page like what exists in Omeka 2 CSV Import. A first query could grab all the Item Types and Item Type Elements, and produce an interface that's analogous to CSV Import's interface to map from column headings to elements. 

That seems extreme in the extreme, though.

**Comment by zerocrates** [comment]
The CSV Import style screen is what I was thinking of by "manual mapping."

**Comment by patrickmj** [comment]
You extremist, you! :)

If we go that route, I'd like the defaults to be what's in the table above to give some guidance and avoid the long dropdown and/or need to implement the property selector somehow, and a class selector.

That seems to me like a lot. Maybe talk about what's in version 1 and version 2 on Monday?

**Comment by patrickmj** [comment]
Of course, we'll need that interface for CSV Import anyway
