### ISSUE TITLE
Test integration with Mapping

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#100]
This tests whether geolocation data gets pulled in when the Mapping module is installed. It will just silently happen -- no configuration or explicit mapping to do.

Using an Omeka Classic site that has items with geolocation data, do an import. The locations should be pulled in along with the item data. 

Additional questions: what happens on a re-import? what happens when S Items have multiple locations, and you do a re-import?

Use Omeka2Importer branch `module-integration`, and Mapping branch `omeka-importer-integration`.

Plus, happy :100:th issue!

**Comment by mebrett** [comment]
Develop branch of S, or master?

**Comment by patrickmj** [comment]
Develop of master

**Comment by patrickmj** [comment]
which makes no sense. develop of S, of course

**Comment by mebrett** [comment]
One thing I'm noticing (and looking back it seems to have been a previous issue that I/we missed) is that imports which fail preserve the comment in the arg but don't display in on the past imports page. Minor bug, but making a note. See jobs 520 and 519 specifically: http://dev.omeka.org/omeka-s/admin/omeka2importer/past-imports

**Comment by mebrett** [comment]
I get following error message on dev.omeka.org/omeka-s if I try to import from `http://meganrbrett.net/make2exhibit/api` : 

`Fatal error: Call to a member function toString() on boolean in /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Controller/IndexController.php on line 260
`

**Comment by patrickmj** [comment]
On the comment being stored thing, that should be fixed in develop, but hasn't been back-merged into the integration branch. See #85 and the commit that closes it.

**Comment by patrickmj** [comment]
The data coming back (or rather, not coming back) is surprising. What version of Omeka is make2exhibit on?

**Comment by patrickmj** [comment]
Possibly related question, what server/hosting company is it on?

**Comment by mebrett** [comment]
2.5.1 (latest of master, I think). On Reclaim.

**Comment by patrickmj** [comment]
Tim at Reclaim changed some things on the servers to fix the problem with the API, so that site's API is working again.

**Comment by mebrett** [comment]
Threw an error: http://dev.omeka.org/omeka-s/admin/job/532/log

**Comment by patrickmj** [comment]
That's getting closer to what's expected, at least. Could you try it again after disabling file validation?

**Comment by mebrett** [comment]
Successful import of 485 items (out of 584 public items according to make2exhibit's dashboard) http://dev.omeka.org/omeka-s/admin/job/533

**Comment by patrickmj** [comment]
Not sure what might be up with the missing 99 items. Might be yet another quirk of the dev server.

The entire 584 came in to my laptop. The big thing is whether the ones that have geolocation data came in okay. I'm look at one that might be okay, but not sure whether it's what's expected.

**Comment by mebrett** [comment]
Aha, apparently the 485 was getting the rest of the site after previous import hit an error: 
![screen shot 2017-05-22 at 2 04 37 pm](https://cloud.githubusercontent.com/assets/2314070/26322133/a55f6e0e-3ef7-11e7-9e35-124560876485.png)

**Comment by mebrett** [comment]
Ran an update on the import from my Reclaim site and it [seems to have gotten stuck](http://dev.omeka.org/omeka-s/admin/job/536)

**Comment by patrickmj** [comment]
Sadly, this might be on the dev server side.

Consistently get MySql server has gone away after the first page

Deactivated Mapping. Switched to master branch of Omeka2Import. Both gave the same result.

**Comment by patrickmj** [comment]
@mebrett a twist that's worth exploring -- in your make2exhibit site, in the API settings, let's try dropping the items per page lower, to maybe 10 or so. Just to see if there's a difference in the amount of data being updated with each database query.

**Comment by mebrett** [comment]
Just set the limit to 10 and will try to update again on dev.omeka.org/omeka-s

**Comment by mebrett** [comment]
Success on that - worth testing changing the per page to a higher number on make2exhibit and using the PerPage setting on the importer?

**Comment by patrickmj** [comment]
Yep! I'd forgotten that the per page setting was already in the branch it's on. But it sounds like that'll cover the bases.

**Comment by mebrett** [comment]
Worked with per page set on the Importer as well

**Comment by patrickmj** [comment]
Yay! So, that's something for us to keep in mind as a problem-solving option.

If the mapping data shows up happily enough, then I think we're all done here.

**Comment by mebrett** [comment]
I'll switch back to the testing branches and give it another go

**Comment by mebrett** [comment]
Updating an import overwrites any mapping changes made - any locations added/changed disappear, revert to whatever was on the source classic install.

**Comment by patrickmj** [comment]
That sounds like the expected behavior on updating.
