### ISSUE TITLE
Test parts of Omeka 2 importer

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#18]
The master branch of Omeka 2 importer could have a few things looked at on the dev install

1. basic import, with and without putting in the API key (check for public vs private items)
2. check importing collections (collections should come in as item sets, with items correctly being assigned to item sets
3. check importing to one 'master' item set. 2 and 3 should be checked separately, and together. When together, items should be assigned to the collection-based item set. separately, items go to the master item set. 'master' item set should also get metadata for dcterms:hasPart

I _think_ the undo feature will work, at least for items, but not item sets.

Until that bug with the login gets fixed on omeka-s develop, if you do `git checkout d73636`, that'll get you to a commit that lets you log in. then, `git checkout develop` will get you back to the latest omeka-s.

**Comment by mebrett** [comment]
A few initial observations: 
1. When you click "Submit" on the module page, there's currently no message that the import has started. The page simply reloads with the input still present. Which is potentially confusion.

2. I tried to import from MallHistories.org both with and without a key and both times it only grabbed the first 50 items. Any idea why?

**Comment by patrickmj** [comment]
Sorry....still had a limit in there from debugging. A new pull of the module should fix that

**Comment by mebrett** [comment]
Also bringing @alyssafahringer on this

**Comment by mebrett** [comment]
@patrickmj - any other api sources you can think of for testing? Esp sites with collections? (besides Mall and my own install?)

**Comment by patrickmj** [comment]
Don't know of any off the top of my head, but setting up your own install(s) with a lot of variation and complexity is always a good thing.

**Comment by alyssafahringer** [comment]
Running into a problem with the importer not importing a collection/item set from my install. 

I used the following link as the endpoint and checked import collections: http://dev.omeka.org/afahring/Omeka/api

I have a collection in my install with 11 items called 'everything' that did not get imported into item sets. I tried both with and without the key and neither brought in the collection.

**Comment by patrickmj** [comment]
@alyssafahringer did the items get imported, but just not put into item sets, or just nothing came in?

**Comment by alyssafahringer** [comment]
The items were imported but not put into the item set.

**Comment by patrickmj** [comment]
hmm....and you checked the 'Import Collections' checkbox?

**Comment by alyssafahringer** [comment]
Yes, and I left the import into dropdown box at select item set

**Comment by patrickmj** [comment]
Uninstall and reinstall of the module made the collections import okay. However, the job stalled at `in_progress`, so more checking and testing is in order, especially from other sites. First guess is that the importer gets confused by empty collections, but that's just a random guess.

**Comment by patrickmj** [comment]
Also notable, there was a botched collection import that left an `[Untitled]` item set. Trying to delete that left a foreign key constraint violation on `omekaimport_record`, so there's something fishy, at least in handling and being able to recover from errors. Haven't reproduced them on my laptop yet, though.

**Comment by patrickmj** [comment]
Superceded by #42
