### ISSUE TITLE
No Undo

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Omeka2Importer#19]
When I tried to undo an import, I got the following: 

There was an error.

exception 'Omeka\Api\Exception\BadRequestException' with message 'The API does not support the "omeka2imports" resource.' in /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php:157
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(36): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#1 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(27): Omeka\Api\Manager->search('omeka2imports', Array)
#2 /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Controller/IndexController.php(54): Omeka\Mvc\Controller\Plugin\Api->search('omeka2imports', Array)
#3 /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Controller/IndexController.php(37): Omeka2Importer\Controller\IndexController->undoJob('30')
#4 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka2Importer\Controller\IndexController->pastImportsAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#15 {main}

**Comment by patrickmj** [comment]
ok. that's not entirely unexpected. I'll see if I can get that done quickly to help with testing before you leave, @mebrett 

Also, the latest core develop branch looks like it fixed the login issue.
