### ISSUE TITLE
Feedback on direction of import interface

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#36]
I've briefly talked about the interface with @kimisgold and @zerocrates , but more eyes is really good at this stage.

On the master branch, I've merged in the interface for mapping Omeka 2 elements onto Omeka S properties. It is still clunky and needs some CSS work, but I want to get feedback before I start locking those things in.

Process right now:
1. On Omeka2Import page, enter an Omeka 2 API endpoing (other options in the form at that stage are optional)
2. Click the link for "Configure mappings" below the form.
3. Wait a bit for data to load -- this is a known UX issue about the AJAX loading
4. Click an element/item type, then click a property/class to add it to the mapping (you'll see more CSS clunkiness there)
5. Hit the 'Import' button.

That should work for importing data. That's not what this testing issue is about, though. I'm more concerned about the interface and workflow for the mapping steps.

**Comment by mebrett** [comment]
![screen shot 2015-10-06 at 12 59 18 pm](https://cloud.githubusercontent.com/assets/2314070/10315750/1929919a-6c2a-11e5-82bf-9e5e41dc1a59.png)

Will there be (should there be) something in the middle column?

**Comment by mebrett** [comment]
Secondly - the "Configure element" text should look more like a button, especially to make it clear that it's not a "press submit to do this" but "click here instead of submit"

**Comment by patrickmj** [comment]
Regarding the 'middle column' question, that should happen if you do step 4, as outlined above

**Comment by mebrett** [comment]
Ah, now I see. That will be something to make clear in the documentation

**Comment by patrickmj** [comment]
Or make more clear on the interface!

**Comment by mebrett** [comment]
I'm getting errors on mapped properties (not classes): see http://dev.omeka.org/omeka-s/admin/item/5791 It's mapping the content correctly but also throwing "Warning: in_array() expects parameter 2 to be array, null given in /websites/omekadev/home/www/omeka-s/modules/MetadataBrowse/Module.php on line 73 " for every property.

**Comment by zerocrates** [comment]
@mebrett make sure you have the latest MetadataBrowse, and then go to Modules and "Configure" it and save. There was a bug that's now fixed.

**Comment by mebrett** [comment]
Ah, thanks. That did fix it. Didn't realize that module was active.
