### ISSUE TITLE
Do we want default mappings from O2 elements to OS HTML Media?

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#44]
A few of the mapping options make sense, e.g. Item Type Metadata Text element to HTML media. Is it worth building those into the defaults, or will that make sorting out the defaults too confusing?

**Comment by jimsafley** [comment]
I don't know enough about how people are using the Text element to have an opinion about whether we should map it to HTML media by default. However, generally, I like the option to map *any* element to HTML media.

**Comment by patrickmj** [comment]
Yep, the option is there for any element and seems to be working.

**Comment by zerocrates** [comment]
I suppose it's possible to go wild and make some of these decisions contingent on whether the specific item currently being ingested used HTML for that element... but maybe that's a bad idea.

I think it's a little hard to say what makes sense as the default. I'd lean a little bit toward not having them.

**Comment by patrickmj** [comment]
Oooh, yeah. I definitely don't want to check if an element uses HTML and decide based on that. There's too much HTML in things that shouldn't be HTML (e.g., descriptions with a YouTube embed). We nicely clean up those issues in S, and I don't want to move backwards.

**Comment by patrickmj** [comment]
Decided: No defaults for you!
