### ISSUE TITLE
Imports not completing

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#46]
Even though all the items appear to get imported, the job never gets to 'completed'

**Comment by patrickmj** [comment]
Solution was to remove the `$em->clear()` that was part of clearing out large memory usage. Question is, will that rebreak that issue ( #45 )?

**Comment by zerocrates** [comment]
Mmm okay, i see, you're ending up clearing out the job row by clearing everything else.

Just removing the clear will get you back to the same problems, but you could instead try specifically detaching the created items in each batch rather than clearing the whole EM.

**Comment by zerocrates** [comment]
job entity, not job row
