### ISSUE TITLE
Omeka 2 Importer not working - job stays in progress status

### ISSUE THREAD

**Issue by mbattou** [omeka-s-modules/Omeka2Importer#49]
I have Omeka s 0.4.0-alpha and I have decided to test this modue to import item/collections from an omeka 2.2 site.
I have made sure that the API was enabled and I have created a super user with an API key (In omeka 2.2).
In omeka s I have installed and activated the module then I fill up the form:
URI: http://localhost/omeka-test/api (I had to figure out the /api from an omeka dev, it was not very obvious)
API key: previously generate for the super user
I select the Item Set I have created for this task and I check the "include" Collection option.

I press "Get Data", a list of items/collections will appear. Then Import.
A job is create and stays at in Progress status.
I press on details: see arguments: and i see elements in the json file. No log file created.
I check the Item set I have created for this task and it says Items(0). Meaning no items were imported.

I will attack a pdf file with more visual so you can have a better understanding.
[GithubReport.pdf](https://github.com/omeka-s-modules/Omeka2Importer/files/57352/GithubReport.pdf)

Thank you!

**Comment by jaguillette** [comment]
I'm running into what might be the same error. I went through the same steps, in making sure that the API was set up, entering the API URL and key, and starting the data transfer.

I was able to see the metadata element mappings, but when I clicked import after that, the job doesn't progress.

I checked the API record on the site I was importing from, and it was accessed when the Omeka S import job started, but not afterwards.

My server logged a few errors on running the job, here they are:
`[Wed Jan 13 21:15:42.710737 2016] [:error] [pid 17437] [client 65.112.8.130:54472] PHP Warning: array_merge(): Argument #2 is not an array in var/www/html/omeka-s/modules/Omeka2Importer/src/Controller/IndexController.php on line 71, referer: http://dighist.fas.harvard.edu/omeka-s/admin/omeka2importer`

`[Wed Jan 13 21:15:42.710767 2016] [:error] [pid 17437] [client 65.112.8.130:54472] PHP Fatal error:  Call to a member function toString() on boolean in /var/www/html/omeka-s/modules/Omeka2Importer/src/Controller/IndexController.php on line 185, referer: http://dighist.fas.harvard.edu/omeka-s/admin/omeka2importer`

**Comment by patrickmj** [comment]
Thanks. And @mbattou, sorry I lost track of this in the run-up and aftermath of holiday break. I'll see what I can uncover.

**Comment by mebrett** [comment]
Continues to be an issue

**Comment by mbattou** [comment]
Megan,

I have not hear back from the devs, so yes, still an ongoing issue.

-- 
*Mohamed Battou*
*Programmeur / Analyste (Division des systèmes**) *
*Programmer / Analyst **(Library Systems Division)*
*Université d'Ottawa |**University of Ottawa *
biblio.uottawa.ca/en
613-562-5800 (4557)

**Comment by patrickmj** [comment]
@mbattou @jaguillette Do either of you have example API endpoints that were causing problems? I've made some revisions, and want to try to check against other problem sites. Thanks!

**Comment by mbattou** [comment]
All I had is on a PDF file I have attached to the git report.

Mohamed.

On Mon, Feb 22, 2016 at 1:14 PM, Patrick Murray-John <
notifications@github.com> wrote:

> @mbattou <https://github.com/mbattou> @jaguillette
> <https://github.com/jaguillette> Do either of you have example API
> endpoints that were causing problems? I've made some revisions, and want to
> try to check against other problem sites. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omeka-s-modules/Omeka2Importer/issues/49#issuecomment-187301405>
> .
>



-- 
*Mohamed Battou*
*Programmeur / Analyste (Division des systèmes**) *
*Programmer / Analyst **(Library Systems Division)*
*Université d'Ottawa |**University of Ottawa *
biblio.uottawa.ca/en
613-562-5800 (4557)

**Comment by jaguillette** [comment]
Hi Patrick, I've got an Omeka 2 API endpoint at http://dighist.fas.harvard.edu/omeka_demo/, and I can email/DM/whatever you a key if you want to give it a try.

**Comment by patrickmj** [comment]
@mbattou @jaguillette Many thanks! We're working on many changes and upgrades, and a new testable set of code should be up soon.

**Comment by mbattou** [comment]
I will definitely test it after the release.
Thank you!

On Tue, Feb 23, 2016 at 3:38 PM, Patrick Murray-John <
notifications@github.com> wrote:

> @mbattou <https://github.com/mbattou> @jaguillette
> <https://github.com/jaguillette> Many thanks! We're working on many
> changes and upgrades, and a new testable set of code should be up soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/omeka-s-modules/Omeka2Importer/issues/49#issuecomment-187891745>
> .
>



-- 
*Mohamed Battou*
*Programmeur / Analyste (Division des systèmes**) *
*Programmer / Analyst **(Library Systems Division)*
*Université d'Ottawa |**University of Ottawa *
biblio.uottawa.ca/en
613-562-5800 (4557)

**Comment by patrickmj** [comment]
@mbattou @jaguillette It won't be publicized until March 15, I suspect, but there are new releases for both core Omeka S and for the Omeka2Importer module.

I hope that they'll address these issues, or at the very least help with the logging to get more info. As always, feedback is very welcome.
Thanks much!
