### ISSUE TITLE
Where to put a 'Next Step' type button

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#51]
From convo with @kimisgold and related #50, there will be a page to just enter the endpoint url, then continue on to the next steps for setting basic import settings and the various mappings.

Does the 'Next' button (or whatever label) belong in to top right, where other actions ('save', 'submit', etc.) live? Or is it not really an action in the same way, and should therefore go somewhere else?

Thoughts @kimisgold @jimsafley @zerocrates ?

**Comment by kimisgold** [comment]
I think its function is akin to the save and submit buttons, so yeah, top right.
