### ISSUE TITLE
Regression check and new UI look

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#55]
Omeka2Importer, develop branch could use a quick look for a couple things

1) just regression check, to make sure it still works on latest omeka-s
2) the redone UI, where it's 1 page to enter the API endpoint, then next page for everything else.

**Comment by mebrett** [comment]
Tried importing, without key, from the Mall site. Nothing's coming in and while the import shows up as a job in the general jobs tab it does not display in the past imports under the module itself.

**Comment by mebrett** [comment]
Compared my dev install with the shared; apparently `phpcli_path` in `local.config.php` must be set to something (other than the default null) in order for Omeka2Importer to work.

**Comment by patrickmj** [comment]
With that fix to the config, are things now coming in and updating okay?

**Comment by mebrett** [comment]
Import is working. If importing content from a site already imported, metadata/mapping is updated. However the jobs aren't registering as complete, in either Jobs or Past Imports. A minor thing, but for anyone with my disposition it's really annoying.

**Comment by patrickmj** [comment]
@mebrett when updating, does it give correct info about how many items were updated?

**Comment by mebrett** [comment]
It's reporting that all the items were "updated" although I've made no changes to the data (tried making changes to one and it still "updated" all)

**Comment by patrickmj** [comment]
might just be a wording change -- updated really means that it existed already, and so was reimported.

**Comment by mebrett** [comment]
I was reading "updated" as "information changed" but the meaning is "reimported with the same item number"? Would renewed be too weird a term?

**Comment by patrickmj** [comment]
"Re-imported" sounds better to me

**Comment by mebrett** [comment]
That works too.
