### ISSUE TITLE
New import settings "batch size" and/or "limit" ?

### ISSUE THREAD

**Issue by jajm** [omeka-s-modules/Omeka2Importer#56]
Actually Omeka2Importer inserts data in database after each page of results.

If the source Omeka API is configured to serve large pages, or if there is a large number of files per item, it can take some time to see the first items appear in Omeka S (a few hours in my case).

It is not ideal if I only want to test the import settings and see the result before I decide to import all items.

What do you think of these 2 new import settings:
- batch size: would set 'per_page' parameter in request urls
- limit: import at most this number of item

**Comment by patrickmj** [comment]
I'm surprised that it took hours to get any import results, but can see the possibility given how much data each page might have to churn through. A `per_page` option could help there, but it would also depend on the original site's per page settings. If you have access to the original site, under Settings->API, you can limit them from there.

The 'limit' idea sounds more workable for the testing context you are talking about. That'd just get it through some and stop. Following up on that, I can see providing a range of item IDs from the original Omeka 2 instance to just try those for testing purposes. That'd make debugging easier, and give a mechanism for checking different variations on item data.

**Comment by jajm** [comment]
> A per_page option could help there, but it would also depend on the original site's per page settings.

I'm not sure to understand that. `per_page` parameter does not override the site setting ?

> If you have access to the original site

Unfortunately, I don't.

>  Following up on that, I can see providing a range of item IDs from the original Omeka 2 instance to just try those for testing purposes.

I just realized that Omeka API provide some filters (collection, itemtype, modified_since, ...). Implementing those filters would totally fit my needs, and would be useful to more people actually. Perhaps better than a range of IDs ?

**Comment by patrickmj** [comment]
I'll have to double check on what origin Omeka site gives precedence to, request params or site settings.

The various filters are there, and would expand the UI greatly if they were to implemented. No doubt they would fit more needs.

Everything S is still in 'alpha', so we're figuring best needs as we go along!

**Comment by patrickmj** [comment]
@jajm Well, almost exactly a year later, but I've returned to some work on the Omeka2importer module and, among other things, it now has a per_page import option on the develop branch.

Limit would be trickier to keep track of what's going on, since there's a distinction between importing new items and updating items already imported. Just keeping track of that distinction with a limit variable would get confusing for UX.
