### ISSUE TITLE
the jobs aren't registering as complete, in either Jobs or Past Imports.

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#58]
per #55

**Comment by patrickmj** [comment]
@mebrett with the latest develop branch of both the module and core, could you confirm the jobs not being listed as complete on a second import on a variety of different sites, like mall, and a variety of the test sites you all have? I'm getting the same result you are for some sites, but not all, so I need help seeing more instances of where it does and does not happen to track it down.

NB 1 The newest develop branch of core makes some changes to the jobs pages, so there's now a separate jobs show page that'll give the link to the job error log (if there is one)

NB 2 this is continuing the same convo about this, but moved to it's own separate issue

**Comment by mebrett** [comment]
A stalled import was displaying as in_progress but without any log info.

**Comment by patrickmj** [comment]
Importing from which sites? I've seen different results for different sites, and am hoping for more info to track down why it does or does not happen.

**Comment by mebrett** [comment]
Stalled on Mall Histories, works on my own sites (from reclaim) and my stuff on dev. Pulling into my own S install.

**Comment by patrickmj** [comment]
Could you give the urls so I can look at the details to try to sort out where the differences might be?

**Comment by mebrett** [comment]
mallhistory.org/api, dev.omeka.org/mebrett/Omeka/api, meganrbrett.net/.make2exhibit/api

**Comment by patrickmj** [comment]
I'd tried your mebrett on dev, and afahring on dev. which both worked as expected.

In a surprise, with the latest of omeka s core and the module on develop branch, mallhistory now seems to work as expected, too. Could you try a new import from that to see if you also get eventually the job showing completion?

**Comment by mebrett** [comment]
I just tried to pull mallhistory.org onto my dev Omeka S install (the one at dev/mebrett) and it didn't work. However! Rather than getting hung up on "In Progress" it shows status "Error" and when I click to view logs, I get the following message:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 614 bytes)
in /websites/omekadev/home/www/mebrett/testomekas/application/src/File/Thumbnailer/GdThumbnailer.php on line 170
```
Similar error on the shared install on dev.

**Comment by mebrett** [comment]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2456 bytes)
in /websites/omekadev/home/www/omeka-s/application/src/File/Thumbnailer/GdThumbnailer.php on line 170  http://dev.omeka.org/omeka-s/admin/job/195/log

**Comment by patrickmj** [comment]
Thanks for both....needed to see what was the same and what was different between them.

I'll try on my install with GdThumbnailer. Might be interesting to see if it works on those other installs with the default 'Omeka\File\ImageMagickThumbnailer', set in local.config.php under 'file_manager'->'thumbnailer'

**Comment by mebrett** [comment]
Changing the file manager - thumbnailer to Image Magick facilitated importing items from mallhistory.org/api. It took a while (more than one minute, less than 10), but it did bring in the data and files.

**Comment by patrickmj** [comment]
awesome. many thanks. that narrows things down quite a bit. Me switching to GD still didn't reproduce it on my laptop, but at least we have a much better sense of where things might be going awry.

**Comment by zerocrates** [comment]
You can absolutely have out-of-memory problems with the GD thumbnailer and big images. I believe it ends up storing a bitmap of the decoded image, which can get pretty big.
