### ISSUE TITLE
Map to Classes Item Type column too wide

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Omeka2Importer#76]
(on branch develop)
The column for Item Type in the tab Map to Omeka S Classes is so wide that the column for classes is hidden under the select resource class sidebar
<img width="948" alt="screen shot 2016-10-27 at 11 23 06 am" src="https://cloud.githubusercontent.com/assets/2314070/19773541/ecf9de2e-9c37-11e6-916e-cb1fa35429e8.png">

**Comment by patrickmj** [comment]
What browser(s) does this happen in? In my FF and Chrome on Linux, it looks like the javascript adjusts spacing ok.

**Comment by mebrett** [comment]
I've done some poking, and here's the sequence:
I enter the api url, go to step 2 (mapping).
If I click over to Map Classes, it looks fine.
However, if I map an element to a property (specifically mapping Date of Birthday to foaf birthday), and then click to map classes, I see this: 
<img width="1029" alt="screen shot 2016-10-27 at 12 01 32 pm" src="https://cloud.githubusercontent.com/assets/2314070/19775132/6849a6c2-9c3d-11e6-8cb4-36b8c18847c2.png">

Clicking on a class opens the sidebar but the rest doesn't shift, causing the weird overlap.
Happens in both Chrome and Firefox for Mac

**Comment by patrickmj** [comment]
Thanks for poking on that. Confirmed on my end that that's happening. Happily, Omeka2Importer isn't on the roadmap for October.

**Comment by zerocrates** [comment]
This is caused by manually setting `active` class on those sidebars rather than using openSidebar. The code doesn't know to check for an open sidebar so it doesn't make space.

**Comment by zerocrates** [comment]
Note also the busted styling of the resource class selector itself.
