### ISSUE TITLE
Beta testing #1

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#81]
A few new features and fixes to look at for the beta:

* Should now be able to assign imported items to multiple item sets
* Should now be able to import Collection data and have that turn into new item sets
* Running the same import should reflect changes both to 1) original site info and 2) different import settings for item sets and collections.

As always with importers, the sticky wickets are in the various possible combinations, so trying out as many combinations to break it is best.

**Comment by mebrett** [comment]
Which branch of master should this testing be done with?

**Comment by patrickmj** [comment]
develop

**Comment by mebrett** [comment]
My imports are getting stuck - http://dev.omeka.org/omeka-s/admin/job
Pulling from Histories of the National Mall returned the error "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1964801 bytes)
in /websites/omekadev/home/www/omeka-s/application/src/File/Thumbnailer/GdThumbnailer.php on line 175" at the end of a very long error log. 

Pulling from my dev site (with collections to Item Sets) seems to have gotten hung up somewhere, although it did at least create the item sets.

**Comment by zerocrates** [comment]
Well that's not good.

The GD thumbnailer is always going to put a little more memory pressure on things because it uses up PHP memory and other thumbnailers don't so much... but using the rest of the 128 MB of memory is probably some memory leak with either our batch create or this specific importer.

**Comment by patrickmj** [comment]
Haven't been able to chase the leak down, but logging has been shushed and now adds info about memory usage, so if you (@mebrett)  could pull develop, try the import, and send a long the info from the log, that'll help.

**Comment by mebrett** [comment]
2016-11-15T18:27:48+00:00 INFO (6): Importing item page 1
2016-11-15T18:28:04+00:00 DEBUG (7): Memory usage: 29926216
2016-11-15T18:28:04+00:00 INFO (6): Importing item page 2
2016-11-15T18:28:19+00:00 DEBUG (7): Memory usage: 32080424
2016-11-15T18:28:19+00:00 INFO (6): Importing item page 3
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1964801 bytes)
in /websites/omekadev/home/www/mebrett/testomekas/application/src/File/Thumbnailer/GdThumbnailer.php on line 175

**Comment by patrickmj** [comment]
@mebrett after much fiddling, we've made changes that _might_ help. We'll still be curious about what shows up in the logs.

**Comment by mebrett** [comment]
Will pulling be sufficient or do I need to reinstall?

**Comment by patrickmj** [comment]
pull is all you'll need

**Comment by mebrett** [comment]
```
2016-11-15T20:08:39+00:00 INFO (6): Importing item page 1
2016-11-15T20:09:02+00:00 DEBUG (7): Memory peak usage: 55934360
2016-11-15T20:09:02+00:00 INFO (6): Importing item page 2
2016-11-15T20:09:22+00:00 DEBUG (7): Memory peak usage: 79073744
2016-11-15T20:09:22+00:00 INFO (6): Importing item page 3
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2456 bytes)
in /websites/omekadev/home/www/omeka-s/application/src/File/Thumbnailer/GdThumbnailer.php on line 171
```
Job is <http://dev.omeka.org/omeka-s/admin/job/329/log>

**Comment by zerocrates** [comment]
I get basically the same results as Megan if I use the GD thumbnailer.

After trying several things to "fix" the problem, some of which I'll push up even though they didn't fix this exact problem, I've arrived at this:

The problematic image is this one: http://mallhistory.org/files/original/4bdfed07a15909cd58f4c4d1764599e5.jpg

It's pretty big, so storing it in uncompressed form would take something like 60 MB by itself. The problem is, PHP is actually using 100+ MB. Add that to the 25-30 MB Omeka and the importer use as a baseline and you run out pretty easily.

I'm not sure why Patrick didn't get these same results on his machine... there could be some difference in PHP or the GD library that avoids that overhead... but I didn't notice even any peaks that would have accounted for the 60 MB loading this file would need at minimum.

Switching the dev server to one of the other thumbnailers is probably the easy answer here... Unless comparing Patrick's results and mine sheds some light on the situation, I'm not sure we really have much we can do about this: GD will always have memory limit problems.

**Comment by patrickmj** [comment]
I was hoping that something might've silently failed with my setup, but Walter here came through okay as an Item in Omeka S with the image and derivatives intact.

**Comment by sharonmleon** [comment]
Is GD the default library?

**Comment by patrickmj** [comment]
Nope. the config distributed uses ImageMagick. GD is often handy to switch to if ImageMagick isn't installed.

**Comment by sharonmleon** [comment]
That's what I thought. Thanks.

**Comment by patrickmj** [comment]
@mebrett OK, it looks like a heaping pile of oddities of GD across different systems that we're have some mitigation for, but not perfect.

So, for going back to the top on the things to look at, could you switch back to `ImageMagickThumbnailer` in the `config/local.config.php` file

```php
        'thumbnailer' => 'Omeka\File\ImageMagickThumbnailer',
```

**Comment by mebrett** [comment]
All the items came in, but with ImageMagick I'm only getting the default file icons, not the thumbnails for the files (which may be why we switched over to GD on dev)

**Comment by patrickmj** [comment]
ok. At least the original stuff in this issue can be tested. We'll have to see if we can figure out what ImageMagick's problem is separately. Anything in the logs?

**Comment by mebrett** [comment]
Yes - http://dev.omeka.org/omeka-s/admin/job/334/log mostly "ERR (3): convert: UnrecognizedAlphaChannelType" over and over

**Comment by mebrett** [comment]
Successful import from mallhistory api, tried it on my dev server sandbox install of classic. The [error log](http://dev.omeka.org/omeka-s/admin/job/335/log) has the same run of 'can't thumbnail' but then is says this: 

```
2016-11-16T19:30:37+00:00 ERR (3): exception 'Doctrine\ORM\ORMInvalidArgumentException' with message 'A new entity was found through the relationship 'Omeka\Entity\Value#resource' that was not configured to cascade persist operations for entity: Omeka\Entity\ItemSet@000000002e7e5a8a0000000061632d5e. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Omeka\Entity\Resource#__toString()' to get a clue.' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(856): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Omeka\Entity\ItemSet))
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(741): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Omeka\Entity\ItemSet))
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(803): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Omeka\Entity\Value))
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Job/Import.php(223): Doctrine\ORM\EntityManager->flush()
#6 /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Job/Import.php(153): Omeka2Importer\Job\Import->importItems(Array)
#7 /websites/omekadev/home/www/omeka-s/modules/Omeka2Importer/src/Job/Import.php(75): Omeka2Importer\Job\Import->importCollections(Array)
#8 /websites/omekadev/home/www/omeka-s/application/src/Job/Strategy/SynchronousStrategy.php(37): Omeka2Importer\Job\Import->perform()
#9 /websites/omekadev/home/www/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#10 /websites/omekadev/home/www/omeka-s/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#11 {main}
```

**Comment by patrickmj** [comment]
I hit some similar stuff recently, but it wasn't quite the same. Have you pulled the latest develop of the importer?

**Comment by mebrett** [comment]
That was on the latest branch

**Comment by patrickmj** [comment]
what's the url to your dev server sandbox of classic ?

**Comment by mebrett** [comment]
dev.omeka.org/mebrett/Omeka

**Comment by patrickmj** [comment]
hmmm...ok.

It looks like there was some kind of item set mapping, which could be either from selecting item sets or from importing collections (or both). Do you remember what options about those you used for the import?

**Comment by mebrett** [comment]
I was doing the import with "Import Collections" checked (Mall Histories doesn't have any collections). I had also selected an Item Set to import into (Omeka2Import Master Set)

**Comment by patrickmj** [comment]
Thanks. It strangely looks like all the items came in, and were mapped to the correct item sets, for both of us. But, I also got that error, so it's a little bit tricky to figure out where it's coming from.

**Comment by zerocrates** [comment]
So are you saying you're both getting the same error? Just by checking the box to import collections?

**Comment by patrickmj** [comment]
looks that way. testing an update without the collections/item sets stuff.

**Comment by mebrett** [comment]
Let me know when it's ready for me to have at again

**Comment by zerocrates** [comment]
I can't reproduce that error. Is this only happening for updates, perhaps?

**Comment by patrickmj** [comment]
Was happening for new import for me. Updating has produced its own new and various problems I'm trying to sort out.

**Comment by patrickmj** [comment]
Suspicion: one or more of the default mappings produces the failure.

What's the call on who's been clicking through to run the import with default mappings, and who's been actively selecting them?

**Comment by zerocrates** [comment]
Mine have all been all-default mappings

**Comment by mebrett** [comment]
I had been using the default mappings plus two additional mappings (First Name to foaf:firstName and Last Name to foaf:LastName)

**Comment by zerocrates** [comment]
#94 should fix the exception Megan reported on collection import.

If you're having trouble reproducing it, make sure to delete all the Sets created by the import. Undo doesn't delete them, and once you've run the import enough times, you won't get the error anymore (it only happens when a new Set is created, and each time you run it without deleting the existing sets, it gets one set "further" until finally they all exist and the error stops happening).
