### ISSUE TITLE
Flash message for undo past import

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Omeka2Importer#82]
When undoing a past import, I think it would be helpful to show a success message that includes the job ID. I realize that there is a column for the job status, but it's a little subtle. It would be consistent with the behavior when importing and also provide a little extra information.

(#81)

**Comment by patrickmj** [comment]
There's a twist that you can check many jobs to undo, and each would get its own undo job id. Maybe just give a more general 'Undo in progress' message without job ids?

**Comment by kimisgold** [comment]
Could the IDs be appended to a single message? "Undo in progress in the following jobs: 3, 4, 5"
