### ISSUE TITLE
Importer doesn't redirect away from Import screen when starting an import

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/Omeka2Importer#84]
You get a flash that the import started, but you're dumped back onto the same form you just filled out. You should probably either go to the front "start a new import" page, the past imports page, or the job status page.

**Comment by patrickmj** [comment]
I think elsewhere it redirects to past imports, so that should be made consistent.

**Comment by jimsafley** [comment]
In core we use a pattern of redirecting to the relevant browse or show page, flashing a message that includes a link back to the add/edit/import page.

**Comment by jimsafley** [comment]
This is how we're doing it: https://github.com/omeka-s-modules/ZoteroImport/commit/dafda17d1decfc3a9c03f73d816c825af6670362

**Comment by zerocrates** [comment]
I'm not sure "Import another?" is wise... it feels like it encourages a rare pattern of having multiple imports happening simultaneously.

**Comment by jimsafley** [comment]
I'm not sure how the message would encourage multiple imports if the user didn't already want to perform another import.
