### ISSUE TITLE
Test fix to #86 across browsers

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#87]
Since this involves both javascript and some subtle UI stuff, it's probably worth a quick check that what John described in #86 is no longer true across browsers. Latest develop branch.

**Comment by mebrett** [comment]
Tried it in Chrome, Safari, and Firefox and got a popup each time with the message "Select an element at the left before choosing a property." If it also gives a popup in IE, then we're good.

**Comment by patrickmj** [comment]
:egg: celent.

**Comment by mebrett** [comment]
Tested on IE, popup works.
