### ISSUE TITLE
Re-imports make destructive changes

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/Omeka2Importer#89]
Among other things:

- Item Set membership is overridden with whatever is specified in the newer import
- All existing media for imported items are deleted and recreated by a reimport so any media added after the fact is deleted

At a minimum this needs _serious_ documentation to note what happens when you import a second time. I'm not particularly convinced that it should work this way generally though, at least by default.

**Comment by zerocrates** [comment]
Also on the topic of things that will need very clear notation minimally: an "undo" of a job that updated records will delete those records. The semantics of "Undo" don't really fit in that case so I'm sure some users will find it surprising.

**Comment by patrickmj** [comment]
I'm not entirely sure what to do about the media getting clobbered with an update. Would I need to dig up the existing media json data, then check each of those to see if it was imported, then only add new media from the import site?
