### ISSUE TITLE
Importing a site with no collections and "Import Collections" checked imports no items

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/Omeka2Importer#92]
At least that's what it seems happens.

I'd expect this to create whatever collections do exist as sets, and to attach them properly to their associated items, but not to exclude items that aren't in any of the collections, and that's what it seems like is happening.

If that's what's happening, then there's also a separate but similar bug that even on sites that _do_ have collections, importing with this option checked could import fewer items than with it unchecked (since it will skip the "uncollected" items).

**Comment by patrickmj** [comment]
I'm pretty sure that the logic basically says _only_ import from collections if that's checked, which is probably not what we want.

**Comment by patrickmj** [comment]
Fixed in https://github.com/omeka-s-modules/Omeka2Importer/commit/b4d9dfb463f9ded265be0fc2538618986a27d384

**Comment by patrickmj** [comment]
missed the alternate approach on the commit comment, so reopenning
