### ISSUE TITLE
Item's link to item set is removed during the import

### ISSUE THREAD

**Issue by jajm** [omeka-s-modules/Omeka2Importer#95]
During the import (when I check "Import collections") the items are correctly linked to item sets, but once the import is completed these links do not exist anymore.

I believe it's because of https://github.com/omeka-s-modules/Omeka2Importer/commit/b4d9dfb463f9ded265be0fc2538618986a27d384 which import twice every item that belongs to a collection.

I reverted this commit, removed all items and items sets and started the import again. This time the links were still there after the end of the import.

**Comment by zerocrates** [comment]
Good point.

[We already want to change that process](https://github.com/omeka-s-modules/Omeka2Importer/commit/b4d9dfb463f9ded265be0fc2538618986a27d384#commitcomment-19891928) but it's good to have one more concrete report of a problem.
