### ISSUE TITLE
Changes to the metadata for a collection are not imported when updating a previous import

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Omeka2Importer#97]
Via #96 

```
Changes to the metadata for a collection are not imported when updating a previous import, even with "import collections" also checked.
```
Might be a problem with how importCollections passes tasks out based on the setting.

**Comment by mebrett** [comment]
To replicate: 1. create a collection with only a title. 2. Add a few items. 3. import into S with collections checked. 4. go back to Omeka Classic site, add in things like description, creator. 5. Reimport into S, with both update previous and import collections checked.
